spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true

logging.level:
  jpabook.jpashop: debug
  org.hibernate.SQL: debug