spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging.level:
  jpabook.jpashop: debug
  org.hibernate.SQL: debug