spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/querydsl?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true # 실행되는 JPQL을 출력

logging:
  level:
    root: info
    study.querydls: debug